/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas_3;

import java.awt.Color;

/**
 *
 * @author Lenovo
 */
public class Perpustakaan extends javax.swing.JFrame {
    
    /**
     * Creates new form Perpustakaan
     */
    public Perpustakaan() {
        initComponents();
        

        cbPilihanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihanBukuActionPerformed(evt);
                // Panggil method untuk mengubah warna latar belakang
                UbahBackgroundColor();
            }
        });
    }
    private void UbahBackgroundColor() {
        // untuk mengambil indeks terpilih dari combo box
        int selectedIndex = cbPilihanBuku.getSelectedIndex();

   
        switch (selectedIndex) {
            case 0:
                txtJudulBuku.setBackground(Color.WHITE); 
                txtNamaPengarang.setBackground(Color.WHITE); 
                txtTahunTerbit.setBackground(Color.WHITE); 
                txtDeskripsi.setBackground(Color.WHITE); 
                break;
            case 1:
                txtJudulBuku.setBackground(new Color(255, 182, 193)); // Light Pink
                txtNamaPengarang.setBackground(Color.WHITE); // White
                txtTahunTerbit.setBackground(new Color(211, 211, 211)); // Light grey
                txtDeskripsi.setBackground(new Color(173, 216, 230)); // Light Blue
                break;
            case 2:
                txtJudulBuku.setBackground(Color.YELLOW);
                txtNamaPengarang.setBackground(new Color(173, 216, 230)); // Light Blue
                txtTahunTerbit.setBackground(new Color(0, 105, 148)); // Oren
                txtDeskripsi.setBackground(new Color(192, 192, 192)); // Light grey
                break;
            case 3:
                txtJudulBuku.setBackground(new Color(255, 182, 193));
                txtNamaPengarang.setBackground(new Color(221, 160, 221)); // Lavender
                txtTahunTerbit.setBackground(new Color(173, 216, 230)); // Light Blue
                txtDeskripsi.setBackground(Color.CYAN); // cyan
                break;
            case 4:
                // Novel Edensor dipilih, ubah warna latar belakang sesuai keinginan
                txtJudulBuku.setBackground(new Color(255, 182, 193)); // Light Pink
                txtNamaPengarang.setBackground(Color.WHITE); // White
                txtTahunTerbit.setBackground(new Color(211, 211, 211)); // Light grey
                txtDeskripsi.setBackground(new Color(173, 216, 230)); // Light Blue
                break;
            default:
                txtJudulBuku.setBackground(getContentPane().getBackground());
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        cbPilihanBuku = new javax.swing.JComboBox<>();
        txtJudulBuku = new javax.swing.JTextField();
        txtNamaPengarang = new javax.swing.JTextField();
        txtTahunTerbit = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        bExit = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 5, 2));

        txtJudul.setBackground(new java.awt.Color(204, 204, 255));
        txtJudul.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        txtJudul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJudul.setText("SIMPLE LIBRARY");
        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });
        getContentPane().add(txtJudul);

        cbPilihanBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbPilihanBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Buku", "Novel Ayah", "Novel Negeri 5 Menara", "Novel Sang Pemimpi", "Novel Edensor" }));
        cbPilihanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihanBukuActionPerformed(evt);
            }
        });
        getContentPane().add(cbPilihanBuku);

        txtJudulBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtJudulBuku.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJudulBuku.setRequestFocusEnabled(false);
        txtJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulBukuActionPerformed(evt);
            }
        });
        getContentPane().add(txtJudulBuku);

        txtNamaPengarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNamaPengarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamaPengarang.setRequestFocusEnabled(false);
        getContentPane().add(txtNamaPengarang);

        txtTahunTerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTahunTerbit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTahunTerbit.setRequestFocusEnabled(false);
        getContentPane().add(txtTahunTerbit);

        txtDeskripsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeskripsi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDeskripsi);

        bExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void cbPilihanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihanBukuActionPerformed
        // TODO add your handling code here:
        String selectedBuku = (String) cbPilihanBuku.getSelectedItem();

        switch (selectedBuku) {
            case "Novel Ayah":
                txtJudulBuku.setText("Judul Buku : Ayah");
                txtNamaPengarang.setText("Nama Pengarang : Andrea Hirata");
                txtTahunTerbit.setText("Tahun Terbit : 2009 ");
                txtDeskripsi.setText(" Novel ini berkisah tentang perjuangan seorang ayah ");
                break;
            case "Novel Negeri 5 Menara":
                txtJudulBuku.setText("Judul Buku : Negeri 5 Menara ");
                txtNamaPengarang.setText("Nama Pengarang : A.Fuadi ");
                txtTahunTerbit.setText("Tahun Terbit : 2009 ");
                txtDeskripsi.setText(" Negeri 5 Menara mengisahkan kisah lima pemuda yang "
                        + "berasal dari berbagai daerah di Indonesia dalam berjuang meraih mimpi.");
                break;
            case "Novel Sang Pemimpi":
                txtJudulBuku.setText("Judul Buku : Sang Pemimpi");
                txtNamaPengarang.setText("Nama Pengarang : Andrea Hirata");
                txtTahunTerbit.setText("Tahun Terbit : 2006 ");
                txtDeskripsi.setText(" Novel ini menceritakan mimpi besar seorang anak untuk mendirikan Sekolah di Desa ");
                break;
            case "Novel Edensor" :
                txtJudulBuku.setText("Judul Buku : Edensor");
                txtNamaPengarang.setText("Nama Pengarang : Andrea Hirata");
                txtTahunTerbit.setText("Tahun Terbit : 2007 ");
                txtDeskripsi.setText(" Novel Edensor merupakan rekaan kisah nyata yang dialami oleh penulis ");
                break;
            default:
                // Handle the case where "Pilih Buku" or unknown item is selected
                txtJudulBuku.setText("");
                txtNamaPengarang.setText("");
                txtTahunTerbit.setText("");
                txtDeskripsi.setText("");
                break;
        }
    }//GEN-LAST:event_cbPilihanBukuActionPerformed

    private void txtJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulBukuActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JComboBox<String> cbPilihanBuku;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtNamaPengarang;
    private javax.swing.JTextField txtTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
